/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// factory_details object
type GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails struct {
	// schematic_id integer
	SchematicId int32 `json:"schematic_id"`
}
