/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// service object
type GetCorporationsCorporationIdStructuresService struct {
	// name string
	Name string `json:"name"`
	// state string
	State string `json:"state"`
}
