/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// contents object
type PutCharactersCharacterIdMailMailIdContents struct {
	// Labels to assign to the mail. Pre-existing labels are unassigned.
	Labels []int32 `json:"labels,omitempty"`
	// Whether the mail is flagged as read
	Read bool `json:"read,omitempty"`
}
