/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// label object
type PostCharactersCharacterIdMailLabelsLabel struct {
	// Hexadecimal string representing label color, in RGB format
	Color string `json:"color,omitempty"`
	// name string
	Name string `json:"name"`
}
