/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// 200 ok object
type GetUniverseGroupsGroupIdOk struct {
	// category_id integer
	CategoryId int32 `json:"category_id"`
	// group_id integer
	GroupId int32 `json:"group_id"`
	// name string
	Name string `json:"name"`
	// published boolean
	Published bool `json:"published"`
	// types array
	Types []int32 `json:"types"`
}
