/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// isk object
type GetCharactersCharacterIdStatsIsk struct {
	// in integer
	In int64 `json:"in,omitempty"`
	// out integer
	Out int64 `json:"out,omitempty"`
}
