/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// content object
type GetCharactersCharacterIdPlanetsPlanetIdContent struct {
	// amount integer
	Amount int64 `json:"amount"`
	// type_id integer
	TypeId int32 `json:"type_id"`
}
