/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// region object
type PostUniverseIdsRegion struct {
	// id integer
	Id int32 `json:"id,omitempty"`
	// name string
	Name string `json:"name,omitempty"`
}
