/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// 200 ok object
type GetUniverseMoonsMoonIdOk struct {
	// moon_id integer
	MoonId int32 `json:"moon_id"`
	// name string
	Name string `json:"name"`
	Position *GetUniverseMoonsMoonIdPosition `json:"position"`
	// The solar system this moon is in
	SystemId int32 `json:"system_id"`
}
