/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// wallet object
type GetCorporationsCorporationIdDivisionsWalletWallet struct {
	// division integer
	Division int32 `json:"division,omitempty"`
	// name string
	Name string `json:"name,omitempty"`
}
