/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// yesterday object
type GetFwLeaderboardsYesterdayYesterday1 struct {
	// Amount of victory points
	Amount int32 `json:"amount,omitempty"`
	// faction_id integer
	FactionId int32 `json:"faction_id,omitempty"`
}
