/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// Summary of victory points gained by the given corporation for the enlisted faction
type GetCorporationsCorporationIdFwStatsVictoryPoints struct {
	// Last week's victory points gained by members of the given corporation
	LastWeek int32 `json:"last_week"`
	// Total victory points gained since the given corporation enlisted
	Total int32 `json:"total"`
	// Yesterday's victory points gained by members of the given corporation
	Yesterday int32 `json:"yesterday"`
}
