/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// Forbidden
type GetContractsPublicItemsContractIdForbidden struct {
	// Forbidden message
	Error_ string `json:"error,omitempty"`
}
